<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE e-supply-tree[
	<!ELEMENT e-supply-tree (tree-node+)>
<!ELEMENT tree-node (hyperLink, name, display-name, status-bar-display?, open-icon?, close-icon?,hot-key?,(tree-node|leaf-node)*)>
<!ELEMENT leaf-node (hyperLink, name, display-name, status-bar-display?, open-icon?, close-icon?,hot-key?, permission-link)>
<!ELEMENT hyperLink (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT display-name    (#PCDATA)>
<!ELEMENT status-bar-display (#PCDATA)>
<!ELEMENT open-icon (#PCDATA)>
<!ELEMENT close-icon (#PCDATA)>
<!ELEMENT permission-link (#PCDATA)>
<!ELEMENT hot-key    (#PCDATA)>
<!ATTLIST hot-key	ctrl  CDATA ""
						shift CDATA ""
						alt   CDATA "" >
]><e-supply-tree>
  <tree-node>
    <hyperLink>ESMenuMainPage</hyperLink>
    <name>eSupply</name>
    <display-name>4s-eSupply</display-name>
    <status-bar-display>SCM CRM from Four Soft</status-bar-display>
    <open-icon>Tree_operations_open.gif</open-icon>
    <close-icon>Tree_operations_open.gif</close-icon>
    <tree-node>
      <hyperLink>ESMenuMainPage</hyperLink>
      <name>eCRM</name>
      <display-name>e-CRM</display-name>
      <status-bar-display>SCM CRM from Four Soft</status-bar-display>
      <open-icon>Tree_operations_open.gif</open-icon>
      <close-icon>Tree_operations_open.gif</close-icon>
      <hot-key ctrl="N" shift="N" alt="N">C</hot-key>
      <tree-node>
        <hyperLink>ESMenuMainPage</hyperLink>
        <name>Setup</name>
        <display-name>Setup</display-name>
        <status-bar-display>Setup</status-bar-display>
        <open-icon>Tree_operations_open.gif</open-icon>
        <close-icon>Tree_operations_open.gif</close-icon>
        <hot-key ctrl="N" shift="N" alt="N">S</hot-key>
        <leaf-node>
          <hyperLink>link=el-crm-Customer-Setup</hyperLink>
          <name>CustomerSetup</name>
          <display-name>Customer Setup</display-name>
          <status-bar-display>Customer Setup</status-bar-display>
          <open-icon>Tree_operations_open.gif</open-icon>
          <close-icon>Tree_operations_open.gif</close-icon>
          <hot-key ctrl="N" shift="Y" alt="N">C</hot-key>
          <permission-link>el-crm-Customer-Setup</permission-link>
        </leaf-node>
      </tree-node>
      <tree-node>
        <hyperLink>ESMenuMainPage</hyperLink>
        <name>Operations</name>
        <display-name>Operations</display-name>
        <status-bar-display>Operations</status-bar-display>
        <open-icon>Tree_operations_open.gif</open-icon>
        <close-icon>Tree_operations_open.gif</close-icon>
        <hot-key ctrl="N" shift="N" alt="N">O</hot-key>
        <leaf-node>
          <hyperLink>link=el-crm-Sales-Order</hyperLink>
          <name>SalesOrder</name>
          <display-name>Sales Order</display-name>
          <status-bar-display>Sales Order</status-bar-display>
          <open-icon>Tree_operations_open.gif</open-icon>
          <close-icon>Tree_operations_open.gif</close-icon>
          <hot-key ctrl="N" shift="Y" alt="N">O</hot-key>
          <permission-link>el-crm-Sales-Order</permission-link>
        </leaf-node>
      </tree-node>
      <leaf-node>
        <hyperLink>link=el-crm-Reports</hyperLink>
        <name>Reports</name>
        <display-name>Reports</display-name>
        <status-bar-display>Reports</status-bar-display>
        <open-icon>Tree_operations_open.gif</open-icon>
        <close-icon>Tree_operations_open.gif</close-icon>
        <hot-key ctrl="N" shift="Y" alt="N">R</hot-key>
        <permission-link>el-crm-Reports</permission-link>
      </leaf-node>
      <leaf-node>
        <hyperLink>link=el-crm-Tracking</hyperLink>
        <name>Tracking</name>
        <display-name>Tracking</display-name>
        <status-bar-display>Tracking</status-bar-display>
        <open-icon>Tree_operations_open.gif</open-icon>
        <close-icon>Tree_operations_open.gif</close-icon>
        <hot-key ctrl="N" shift="Y" alt="N">T</hot-key>
        <permission-link>el-crm-Tracking</permission-link>
      </leaf-node>
    </tree-node>



    <tree-node>
      <leaf-node>
        <name>Operations</name>
        <permission-link>es-etc-Operations</permission-link>
      </leaf-node>
      <leaf-node>
        <name>Order Management</name>
        <permission-link>es-etc-OrderManagement</permission-link>
      </leaf-node>
      <leaf-node>
        <name>SFA</name>
        <permission-link>es-etc-sfa</permission-link>
      </leaf-node>
      <leaf-node>
        <name>Track &amp; Trace</name>
        <permission-link>es-etc-TrackNTrace</permission-link>
      </leaf-node>
      <leaf-node>
        <name>Operational Reports</name>
        <permission-link>es-etc-OperationalReports</permission-link>
      </leaf-node>
      <leaf-node>
        <name>Customer Reports</name>
        <permission-link>es-etc-CustomerReports</permission-link>
      </leaf-node>
      <leaf-node>
        <name>Print Reports</name>
        <permission-link>es-etc-PrintReports</permission-link>
      </leaf-node>
    </tree-node>
  </tree-node>
</e-supply-tree>
